/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pill.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/pill.glb')
  const { ref, mixer,names, actions, clips } = useAnimations(animations, group)
  useEffect(() => {
    actions['Action'].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="pillbottom" geometry={nodes.pillbottom.geometry} material={materials.greenpill} />
        <mesh name="capsuletop" geometry={nodes.capsuletop.geometry} material={materials.capsule}>
          <mesh name="pilltop" geometry={nodes.pilltop.geometry} material={materials.greenpill} />
        </mesh>
        <mesh name="capsulebottom" geometry={nodes.capsulebottom.geometry} material={materials.capsule} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials.metal} position={[0, 0, 0.255]} scale={0} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/pill.glb')